name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - blueprints/defentions/*
    - blueprints/deployment/blueprints_defentions.yml
    exclude:
    - blueprints/defenitions/versions.json

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage : Build
    jobs:
      - job: Build
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/blueprints/
              artifact: blueprints
  - stage : Deploy
    jobs:
      - deployment:  Deploy_Tenant
        environment: tenant-demo
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Monitoring Infra Blueprint
                  inputs:
                    azureSubscription: 'yesoreyeram-demo-helloplatform_governance'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment mg create --name "$(Build.BuildId)" --management-group-id Hello --location WestUS --template-file "$(Pipeline.Workspace)/blueprints/defenitions/monitoring-infrastructure.json"
                      exit $LASTEXITCODE;

                - task: AzureCLI@2
                  displayName: Security Blueprint
                  inputs:
                    azureSubscription: 'yesoreyeram-demo-helloplatform_governance'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment mg create --name "$(Build.BuildId)" --management-group-id Hello --location WestUS --template-file "$(Pipeline.Workspace)/blueprints/defenitions/security.json"
                      exit $LASTEXITCODE;

                - task: AzureCLI@2
                  displayName: Network Blueprint
                  inputs:
                    azureSubscription: 'yesoreyeram-demo-helloplatform_governance'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment mg create --name "$(Build.BuildId)" --management-group-id Hello --location WestUS --template-file "$(Pipeline.Workspace)/blueprints/defenitions/network.json"
                      exit $LASTEXITCODE;

                - task: AzureCLI@2
                  displayName: Devops Blueprint
                  inputs:
                    azureSubscription: 'yesoreyeram-demo-helloplatform_governance'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment mg create --name "$(Build.BuildId)" --management-group-id Hello --location WestUS --template-file "$(Pipeline.Workspace)/blueprints/defenitions/devops.json"
                      exit $LASTEXITCODE;
  