name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - arm-templates/tenant_with_management_groups.json
    - azure-pipelines/tenant_with_management_groups.yml

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage : Build
    jobs:
      - job: Build
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/arm-templates/
              artifact: arm-templates
  - stage : Deploy
    jobs:
      - deployment:  Deploy_Tenant
        environment: tenant-demo
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'yesoreyeram-demo-demo-tenant-contributor'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment tenant create --name demoTenantDeployment --location WestUS --template-file "$(Pipeline.Workspace)/arm-templates/tenant_with_management_groups.json"
                      exit $LASTEXITCODE;
